# Generated by Django 3.1.7 on 2021-03-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildBackground',
            fields=[
                ('childname', models.CharField(db_column='childName', max_length=20)),
                ('childage', models.IntegerField(blank=True, db_column='childAge', null=True)),
                ('childoccupation', models.CharField(blank=True, db_column='childOccupation', max_length=20, null=True)),
                ('childid', models.IntegerField(db_column='childId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'child_background',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentid', models.IntegerField(db_column='documentId', primary_key=True, serialize=False)),
                ('documentname', models.CharField(db_column='documentName', max_length=50)),
                ('dateandtimecreated', models.DateTimeField(db_column='dateAndTimeCreated')),
                ('author', models.CharField(max_length=50)),
                ('dateandtimelastedited', models.DateTimeField(blank=True, db_column='dateAndTimeLastEdited', null=True)),
                ('recenteditor', models.CharField(blank=True, db_column='recentEditor', max_length=50, null=True)),
                ('preparedby', models.CharField(db_column='preparedBy', max_length=20)),
                ('preparationdate', models.DateTimeField(db_column='preparationDate')),
                ('notedby', models.CharField(db_column='notedBy', max_length=20)),
                ('noteddate', models.DateTimeField(db_column='notedDate')),
                ('approvedby', models.CharField(db_column='approvedBy', max_length=20)),
                ('approveddate', models.DateTimeField(db_column='approvedDate')),
                ('receivedby', models.CharField(db_column='receivedBy', max_length=20)),
                ('receiveddate', models.DateTimeField(db_column='receivedDate')),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('highestdegree', models.CharField(blank=True, db_column='highestDegree', max_length=20, null=True)),
                ('schoolname', models.CharField(db_column='schoolName', max_length=20)),
                ('startingyearattended', models.DateField(db_column='startingYearAttended')),
                ('endingyearattended', models.DateField(db_column='endingYearAttended')),
                ('schooltype', models.CharField(db_column='schoolType', max_length=15)),
                ('degreeid', models.IntegerField(db_column='degreeId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'educational_background',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyDetails',
            fields=[
                ('emergencycontactnumber', models.IntegerField(db_column='emergencyContactNumber', primary_key=True, serialize=False)),
                ('emergencycontactname', models.CharField(db_column='emergencyContactName', max_length=20)),
                ('emergencyrelationship', models.CharField(blank=True, db_column='emergencyRelationship', max_length=20, null=True)),
                ('emergencyaddress', models.CharField(db_column='emergencyAddress', max_length=50)),
            ],
            options={
                'db_table': 'emergency_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('employeename', models.CharField(db_column='employeeName', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField(db_column='birthDate')),
                ('civilstatus', models.CharField(db_column='civilStatus', max_length=10)),
                ('citizenship', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('bloodtype', models.CharField(db_column='bloodType', max_length=10)),
                ('numberofdependent', models.IntegerField(db_column='numberOfDependent')),
                ('presentaddress', models.CharField(db_column='presentAddress', max_length=100)),
                ('permanentaddress', models.CharField(db_column='permanentAddress', max_length=100)),
                ('contactnumber', models.IntegerField(db_column='contactNumber')),
                ('informationid', models.IntegerField(db_column='informationId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee_personal_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('position', models.CharField(max_length=20)),
                ('jobid', models.IntegerField(db_column='jobId', primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePositionHistory',
            fields=[
                ('previousdepartment', models.CharField(db_column='previousDepartment', max_length=20)),
                ('previousposition_one', models.CharField(db_column='previousPosition_One', max_length=20)),
                ('previousbranch', models.CharField(db_column='previousBranch', max_length=20)),
                ('year', models.TextField()),
                ('pastpositionid', models.IntegerField(db_column='pastPositionId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee_position_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkLocation',
            fields=[
                ('branch', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee_work_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('previouscompanyname', models.CharField(db_column='previousCompanyName', max_length=20)),
                ('previousposition', models.CharField(blank=True, db_column='previousPosition', max_length=20, null=True)),
                ('reasonforleaving', models.CharField(blank=True, db_column='reasonForLeaving', max_length=20, null=True)),
                ('companycontactnumber', models.CharField(blank=True, db_column='companyContactNumber', max_length=20, null=True)),
                ('withcoeorclearance', models.CharField(db_column='withCOEorClearance', max_length=10)),
                ('employmenthistoryid', models.IntegerField(db_column='employmentHistoryId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employment_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberBackground',
            fields=[
                ('membername', models.CharField(db_column='memberName', max_length=20)),
                ('memberage', models.IntegerField(blank=True, db_column='memberAge', null=True)),
                ('memberrelationship', models.CharField(db_column='memberRelationship', max_length=20)),
                ('memberoccupation', models.CharField(blank=True, db_column='memberOccupation', max_length=20, null=True)),
                ('familyid', models.IntegerField(db_column='familyId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'family_member_background',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('memoreferencenumber', models.IntegerField(db_column='memoReferenceNumber', primary_key=True, serialize=False)),
                ('recordname', models.CharField(db_column='recordName', max_length=20)),
                ('memodate', models.DateField(blank=True, db_column='memoDate', null=True)),
                ('issuingbranch', models.CharField(db_column='issuingBranch', max_length=20)),
                ('recorddescription', models.CharField(blank=True, db_column='recordDescription', max_length=20, null=True)),
                ('recordtype', models.CharField(db_column='recordType', max_length=15)),
                ('issuingdepartment', models.CharField(db_column='issuingDepartment', max_length=20)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpouseBackground',
            fields=[
                ('spousename', models.CharField(db_column='spouseName', max_length=20)),
                ('spousecompany', models.CharField(blank=True, db_column='spouseCompany', max_length=20, null=True)),
                ('spousecompanyaddress', models.CharField(blank=True, db_column='spouseCompanyAddress', max_length=20, null=True)),
                ('numberofchildren', models.IntegerField(blank=True, db_column='numberOfChildren', null=True)),
                ('spouseid', models.IntegerField(db_column='spouseId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'spouse_background',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('amemoreferencenumber', models.OneToOneField(db_column='aMemoReferenceNumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginapp.record')),
                ('awardissuer', models.CharField(db_column='awardIssuer', max_length=20)),
                ('awardpurpose', models.CharField(db_column='awardPurpose', max_length=20)),
                ('awardtype', models.CharField(db_column='awardType', max_length=20)),
            ],
            options={
                'db_table': 'awards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.OneToOneField(db_column='employeeId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginapp.document')),
                ('startdate', models.DateTimeField(db_column='startDate')),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('employmentstatus', models.CharField(db_column='employmentStatus', max_length=15)),
                ('salarytype', models.CharField(db_column='salaryType', max_length=10)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noac',
            fields=[
                ('nmemoreferencenumber', models.OneToOneField(db_column='nMemoReferenceNumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginapp.record')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('noactype', models.CharField(db_column='noacType', max_length=15)),
                ('sanction', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'noac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Awol',
            fields=[
                ('noofoffense', models.IntegerField(db_column='noOfOffense')),
                ('hearingdate', models.DateTimeField(blank=True, db_column='hearingDate', null=True)),
                ('wnmemoreferencenumber', models.OneToOneField(db_column='wNMemoReferenceNumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginapp.noac')),
            ],
            options={
                'db_table': 'awol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorOffense',
            fields=[
                ('hearingdate', models.DateTimeField(blank=True, db_column='hearingDate', null=True)),
                ('mnmemoreferencenumber', models.OneToOneField(db_column='mNMemoReferenceNumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginapp.noac')),
            ],
            options={
                'db_table': 'major_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timekeeping',
            fields=[
                ('noofoffense', models.IntegerField(db_column='noOfOffense')),
                ('tnmemoreferencenumber', models.OneToOneField(db_column='tNMemoReferenceNumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginapp.noac')),
            ],
            options={
                'db_table': 'timekeeping',
                'managed': False,
            },
        ),
    ]
